---
title: "bootstrapping"
author: "Marcell Püski"
date: '2022 szeptember 29 '
output: html_document
---

# load libraries
```{r}
library(tidyverse)
library(data.table)
library(car)
library(survival)
library(lfe)
library(miceadds)
library(boot)
library(ds4psy)
library(knitr)

```

# load data
```{r}
metadata = data.table(read.csv("../../data/pptdata.csv"))

metadata[,intervention:=as.numeric(week %in% c(1:4))]

```


# data during intervention

```{r}
##-----Data during intervention-----:
metadata_during = metadata[week<=4 & week >= -52]
##Create weights:
#~~~T_i: length of panel of respective individual
#~~~Lc : length of respective cohort
#~~~Ngc: number of participants in respective group and cohort
metadata_during[,T_i:=.N, by = participant_id]
metadata_during[,time_weight:=as.numeric(Lc)/(T_i * Ngc)]
metadata_during = metadata_during[order(participant_id)]
metadata_during[,ind_weight:=1/T_i]
##Relevel factors so the Placebe Control is the reference group
metadata_during[,exp_condition:=as.factor(exp_condition)]
metadata_during[,exp_condition:=relevel(exp_condition, ref = "Placebo Control")]
metadata_during[,treatment_number:=as.numeric(exp_condition)]

```


# function in original study to calculate best intervantions

```{r}
meta_regression_free = function(dt, period = "during", weight = "time", dv = "visits", robust = "none", ref = 'control'){
  ## period: either during, 4-week post-intervention or 10-week post-intervention
  ## weight: time-weighted (main one) or individual-weighted (robustness check #3)
  ## dv    : binary (whether visited the gym during a given week) or visits (weekly gym visits)
  ## robust: specify what robustness check to run (default to 'none' for main analysis)
  ## ref   : the reference treatment group, either "control" for Placebo Control or "mintreat" for Planning, Reminders and Micro-Incentives
  if(period == "during"){data = copy(dt)} 
  if(period == "4post"){data = copy(metadata_4post)}
  if(period == "10post"){data = copy(metadata_10post)}
  if(dv == "visits"){data[,dv:=visits]}; if(dv == "binary"){data[,dv:=any_visit]} # specify dv
  if(robust == "intended"){ 
    ## Robustness check #1: Using intended treatment instead of assigned treatment
    data[,intended_exp_condition:=as.character(intended_exp_condition)]
    data[,intended_exp_condition:=relevel(as.factor(intended_exp_condition), ref = "Placebo Control")]
    data[,exp_condition:=intended_exp_condition]
    data[,treatment_number:=as.numeric(intended_exp_condition)]
    data[,Ngc_intended:=uniqueN(participant_id), list(exp_condition, cohort)]
    data[,time_weight:=as.numeric(Lc)/(Ngc_intended*T_i)]
  }
  if(robust == "collapse"){ 
    ## Robustness check #2: Without collapsing different versions of Planning, Reminders & Micro-incentives
    data[treatment == "1241C", exp_condition:="Planning, Reminders & Micro-Incentives to Exercise II"]
    data[treatment == "1253A", exp_condition:="Planning, Reminders & Micro-Incentives to Exercise III"]
    data[,treatment_number:=as.numeric(as.factor(exp_condition))]
    data[,Ngc_collapse:=uniqueN(participant_id), list(exp_condition, cohort)]
    data[,time_weight:=as.numeric(Lc)/(Ngc_collapse * T_i)]
  }
  if(weight == "time"){W = data$time_weight};  ## The main weighting scheme used throughout
  if(weight == "ind"){
    ## Robustness check #3: Obs weighted by individuals
    W = data$ind_weight
  }  
  if(period %in% c("4post", "10post") ){
    ## Post-intervention period data
    main_reg = felm(dv~factor(treatment_number)*intervention +
                      factor(treatment_number)*post_intervention|
                      factor(week):factor(cohort) + factor(participant_id)|0|
                      participant_id, data = data, weights = W,
                    exactDOF = TRUE)
    coeff     = coef(main_reg)
    main_coef = coeff[!is.nan(coeff)]
    
    coef_table = data.table(name = names(main_coef), est = main_coef)
    coef_table[,treatment_number:=gsub("factor(treatment_number)", "", name, fixed = TRUE)]
    coef_table[,treatment_number:=gsub(":post_intervention", "", treatment_number, fixed = TRUE)]
    coef_table[,treatment_number:=as.numeric(treatment_number)]
  }
  if(period == "during"){
    ## During intervention data
    main_reg = felm(dv~factor(treatment_number)*intervention|factor(week):factor(cohort) + factor(participant_id)|0|
                      participant_id, data = data, weights = W,
                    exactDOF = TRUE)
    coeff     = coef(main_reg)
    main_coef = coeff[!is.nan(coeff)]
    
    coef_table = data.table(name = names(main_coef), est = main_coef)
    coef_table[,treatment_number:=gsub("factor(treatment_number)", "", name, fixed = TRUE)]
    coef_table[,treatment_number:=gsub(":intervention", "", treatment_number, fixed = TRUE)]
    coef_table[,treatment_number:=as.numeric(treatment_number)]
  }
  ## Get clustered standard errors:
  HCmatrix = main_reg$clustervcv
  HCmatrix = HCmatrix[!is.na(coef(main_reg)),!is.na(coef(main_reg))]
    
  #----Wald tests---:
  ## This is to get pairwise Wald tests of coefficients to compare the experimental conditions
  H = rep(0, nrow(coef_table))
  G = length(unique(coef_table[!is.na(treatment_number)]$treatment_number))+1
  est_compare  = matrix(0, G, G)
  sd_compare   = matrix(0, G, G)
  pval_compare = matrix(0, G, G)
  ## some formatting below:
  for(t1 in 2:G){
    for(t2 in (1:(G-1))){
      H = rep(0, nrow(coef_table))
      H[coef_table[treatment_number==t1, which = TRUE]] = 1
      H[coef_table[treatment_number==t2, which = TRUE]] = -1
      est_compare[t1,t2]  = H %*% coef_table$est
      sd_compare[t1,t2]   = sqrt(c(HCmatrix %*% H) %*% H)
      pval_compare[t1,t2] =  linearHypothesis(main_reg, hypothesis.matrix = H, test = 'Chisq', vcov. = HCmatrix,
                                                singular.ok = TRUE)$`Pr(>Chisq)`[2]
    }
  }
  correct_est = function(X){
      X[,G]   = -X[G,]
      X[1,]   = -X[,1]
      diag(X) = 0
      return(X)
  }
  correct_err = function(X){
      X[,G]   = X[G,]
      X[1,]   = X[,1]
      diag(X) = 0
      return(X)
  }
    
  est_compare  = correct_est(est_compare)
  sd_compare   = correct_err(sd_compare)
  pval_compare = correct_err(pval_compare)
  #-----Create table of coefficients-----:
  treatment_code = data[,.(treatment_number = treatment_number[1]), 
                        factor(exp_condition)]
  treatment_code = treatment_code[order(treatment_number)]
  if(ref == "control"){ # If the reference group is "Placebo Control"
    treatment_code[,coef:=round(est_compare[,1], 3)]
    treatment_code[,sd:=round(sd_compare[,1], 3)]
    treatment_code[,pval:=round(pval_compare[,1], 3)]  
  }
    
    
  if(ref == 'mintreat'){# If the reference group is "Planning, Reminders, and Micro-Incentives"
    treatment_code[,coef:=round(est_compare[,44], 3)] 
    treatment_code[,sd:=round(sd_compare[,44], 3)]
    treatment_code[,pval:=round(pval_compare[,44], 3)]
    
  }
  ## %outperformed significantly:
  est_better   = est_compare  > 0
  pval_better5 = pval_compare < 0.05
  better5 = est_better * pval_better5
    
  ## Rsquared:
  a  = summary(main_reg)
  r2 = c(a$r.squared, a$adj.r.squared)
  return(list("model" = main_reg, 
                "r2"    = r2,
                "coef"  = treatment_code,
                "outperform" = better5,
                "pval_pairs" = pval_compare)) 
}



```

# for loop creating bootstrapt data sets

```{r}

v <- list()

for (i in 1:100) {
  
  q <- metadata_during %>%
  group_by(exp_condition) %>%
  distinct(participant_id) %>%
  sample_n(., size = 200, replace = FALSE)
  
  q <- q$participant_id
  
  v[[i]] <- data.table(metadata_during %>%
  filter(participant_id %in% q))
  
}


```

# analyse bootstrapped data sets by original analyses

```{r}
results <- list()

for (i in 1:length(v)) {
  
  dt <- v[[i]]
  
  a = meta_regression_free(dt)
  
  results[[i]] <- a$coef
  
}

```

# sorting results

```{r}
results_tidy <- results

for (i in 1:length(results_tidy)) {
  
  results_tidy[[i]] <- results_tidy [[i]]%>%
    arrange(desc(coef))
  
}

```

# counting of first places

```{r}
first_place <- c()

for (i in 1:length(results_tidy)) {
  
  first_place[i] <- results_tidy[[i]][1,2]
  
}

first_place <- unlist(first_place)

```

# create data separetly - for saving

```{r}

for(i in 1:length(results_tidy)) {                    
  assign(paste0("data_", i), results_tidy[[i]])
}

# save data name in list
names <- c()

for(i in 1:length(results_tidy)) {                    
  names[i] <- paste0("data_", i)
}

```

# save results

```{r}

for(i in 1:length(names)) {                              
  write_excel_csv(get(names[i]),                              
             paste0("../../data/bootstrapping/",
                    names[i],
                    ".csv"),
             na = "NA", append = FALSE,
  col_names = TRUE, delim = ",")
}

```

